# Generated by Django 5.0.9 on 2026-08-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "registry",
            "0002_modelversion_algorithm_name_modelversion_changelog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("interval_seconds", models.IntegerField(default=30)),
                ("batch_size", models.IntegerField(default=500)),
                ("include_labels", models.BooleanField(default=True)),
                ("drift_plan", models.JSONField(default=dict)),
                (
                    "holdout_file",
                    models.FileField(
                        blank=True, null=True, upload_to="simulator/holdouts/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STOPPED", "Stopped"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                        ],
                        default="STOPPED",
                        max_length=20,
                    ),
                ),
                ("next_batch_index", models.IntegerField(default=0)),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="registry.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
