# Generated by Django 5.0.9 on 2026-08-17 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("target_column", models.CharField(max_length=255)),
                (
                    "positive_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("BINARY", "Binary Classification"),
                            ("MULTICLASS", "Multiclass Classification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="owned_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model",
                "verbose_name_plural": "ML Models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MODEL_CREATED", "Model Created"),
                            ("VERSION_UPLOADED", "Version Uploaded"),
                            ("VERSION_ACTIVATED", "Version Activated"),
                            ("VERSION_DEACTIVATED", "Version Deactivated"),
                            ("VERSION_ARCHIVED", "Version Archived"),
                            ("BASELINE_UPLOADED", "Baseline Uploaded"),
                            ("THRESHOLDS_CHANGED", "Thresholds Changed"),
                            ("MODEL_DEACTIVATED", "Model Deactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="registry.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.IntegerField(default=1)),
                ("label", models.CharField(max_length=50)),
                ("artifact", models.FileField(upload_to="models/artifacts/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("feature_schema", models.JSONField(default=dict)),
                ("training_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "baseline_prediction_distribution",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="registry.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("ml_model", "version_number")},
            },
        ),
    ]
