# Generated by Django 5.0.9 on 2026-08-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="algorithm_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="changelog",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="validation_message",
            field=models.TextField(blank=True),
        ),
    ]
