# Generated by Django 5.0.9 on 2026-08-17 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.IntegerField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DRIFT", "Drift"),
                            ("PERFORMANCE", "Performance"),
                            ("QUALITY", "Quality"),
                            ("HEALTH", "Health"),
                            ("RETRAIN", "Retrain"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feature_name", models.CharField(blank=True, max_length=255)),
                ("headline", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("occurrence_count", models.IntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="registry.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="RetrainRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("ADVISED", "Advised"), ("URGENT", "Urgent")],
                        max_length=20,
                    ),
                ),
                ("triggers", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrain_recommendations",
                        to="registry.mlmodel",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrain_recommendations",
                        to="registry.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThresholdProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ks_p_value_threshold", models.FloatField(default=0.05)),
                ("chi2_p_value_threshold", models.FloatField(default=0.05)),
                ("psi_threshold", models.FloatField(default=0.2)),
                ("js_threshold", models.FloatField(default=0.1)),
                ("missing_value_rate_threshold", models.FloatField(default=0.05)),
                ("duplicate_row_rate_threshold", models.FloatField(default=0.01)),
                ("outlier_rate_threshold", models.FloatField(default=0.05)),
                ("accuracy_drop_threshold", models.FloatField(default=0.05)),
                ("health_warning_threshold", models.IntegerField(default=70)),
                ("health_critical_threshold", models.IntegerField(default=50)),
                (
                    "ml_model",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold_profile",
                        to="registry.mlmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
