# Generated by Django 5.0.9 on 2026-08-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        (
            "registry",
            "0002_modelversion_algorithm_name_modelversion_changelog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thresholdprofile",
            name="accuracy_drop_threshold",
        ),
        migrations.RemoveField(
            model_name="thresholdprofile",
            name="chi2_p_value_threshold",
        ),
        migrations.RemoveField(
            model_name="thresholdprofile",
            name="js_threshold",
        ),
        migrations.RemoveField(
            model_name="thresholdprofile",
            name="ks_p_value_threshold",
        ),
        migrations.RemoveField(
            model_name="thresholdprofile",
            name="psi_threshold",
        ),
        migrations.AddField(
            model_name="alert",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolution_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retrain_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="run_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="accuracy_drop_major",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="accuracy_drop_minor",
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="alert_cooldown_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="alpha",
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="jsd_high",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="jsd_moderate",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="min_samples",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="moderate_ratio_for_high",
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="psi_high",
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name="thresholdprofile",
            name="psi_moderate",
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name="thresholdprofile",
            name="health_critical_threshold",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="thresholdprofile",
            name="health_warning_threshold",
            field=models.IntegerField(default=80),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["ml_model", "status", "category", "feature_name"],
                name="alert_dedup_idx",
            ),
        ),
    ]
