# Generated by Django 5.0.9 on 2026-08-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_remove_thresholdprofile_accuracy_drop_threshold_and_more"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="retrainrecommendation",
            name="run_id",
        ),
        migrations.AddField(
            model_name="alert",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="monitoring.monitoringrun",
            ),
        ),
        migrations.AddField(
            model_name="retrainrecommendation",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retrain_recommendations",
                to="monitoring.monitoringrun",
            ),
        ),
    ]
