# Generated by Django 5.0.9 on 2026-08-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        (
            "registry",
            "0002_modelversion_algorithm_name_modelversion_changelog_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("UPLOAD", "Upload"),
                            ("API", "API"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "overall_drift_status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("INSUFFICIENT_DATA", "Insufficient Data"),
                        ],
                        default="NONE",
                        max_length=25,
                    ),
                ),
                ("features_total", models.IntegerField(default=0)),
                ("features_high", models.IntegerField(default=0)),
                ("features_moderate", models.IntegerField(default=0)),
                ("features_insufficient", models.IntegerField(default=0)),
                ("health_score", models.IntegerField(blank=True, null=True)),
                ("health_raw_score", models.IntegerField(blank=True, null=True)),
                ("health_capped", models.BooleanField(default=False)),
                (
                    "health_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("health_components", models.JSONField(blank=True, default=dict)),
                ("labels_available", models.BooleanField(default=False)),
                ("thresholds_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "data_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run",
                        to="datasets.databatch",
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="registry.mlmodel",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="registry.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureDriftResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=255)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric"),
                            ("CATEGORICAL", "Categorical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "test_name",
                    models.CharField(
                        blank=True,
                        choices=[("KS", "Kolmogorov-Smirnov"), ("CHI2", "Chi-Square")],
                        max_length=10,
                    ),
                ),
                ("test_statistic", models.FloatField(blank=True, null=True)),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("psi", models.FloatField(blank=True, null=True)),
                ("jsd", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("INSUFFICIENT_DATA", "Insufficient Data"),
                        ],
                        default="NONE",
                        max_length=25,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("baseline_summary", models.JSONField(blank=True, default=dict)),
                ("current_summary", models.JSONField(blank=True, default=dict)),
                ("unseen_categories", models.JSONField(blank=True, default=list)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_results",
                        to="monitoring.monitoringrun",
                    ),
                ),
            ],
            options={
                "ordering": ["feature_name"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("columns_checked", models.IntegerField(default=0)),
                ("missing_total", models.IntegerField(default=0)),
                ("missing_pct", models.FloatField(default=0.0)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("duplicate_pct", models.FloatField(default=0.0)),
                ("outlier_pct", models.FloatField(default=0.0)),
                ("type_mismatch_columns", models.JSONField(blank=True, default=dict)),
                ("unseen_category_columns", models.JSONField(blank=True, default=dict)),
                ("out_of_range_columns", models.JSONField(blank=True, default=dict)),
                ("outlier_counts", models.JSONField(blank=True, default=dict)),
                ("per_column", models.JSONField(blank=True, default=dict)),
                ("penalties", models.JSONField(blank=True, default=dict)),
                ("quality_score", models.IntegerField(default=100)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality",
                        to="monitoring.monitoringrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labels_available", models.BooleanField(default=False)),
                ("sample_count", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("error_rate", models.FloatField(blank=True, null=True)),
                ("precision_positive", models.FloatField(blank=True, null=True)),
                ("recall_positive", models.FloatField(blank=True, null=True)),
                ("f1_positive", models.FloatField(blank=True, null=True)),
                ("precision_macro", models.FloatField(blank=True, null=True)),
                ("recall_macro", models.FloatField(blank=True, null=True)),
                ("f1_macro", models.FloatField(blank=True, null=True)),
                ("positive_class", models.CharField(blank=True, max_length=100)),
                ("confusion_matrix", models.JSONField(blank=True, null=True)),
                ("prediction_distribution", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="monitoring.monitoringrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="monitoringrun",
            index=models.Index(
                fields=["ml_model", "-created_at"],
                name="monitoring__ml_mode_928a7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringrun",
            index=models.Index(
                fields=["ml_model", "status"], name="monitoring__ml_mode_862c42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featuredriftresult",
            index=models.Index(
                fields=["run", "status"], name="monitoring__run_id_068ce6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featuredriftresult",
            unique_together={("run", "feature_name")},
        ),
    ]
